package Entities.behavior;

/*Generated by MPS */


public class BlackNode_BehaviorDescriptor extends Node_BehaviorDescriptor {
  public BlackNode_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "Entities.structure.BlackNode";
  }
}
