package Entities.behavior;

/*Generated by MPS */


public class OrangeEdge_BehaviorDescriptor extends Edge_BehaviorDescriptor {
  public OrangeEdge_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "Entities.structure.OrangeEdge";
  }
}
