package Entities.behavior;

/*Generated by MPS */


public class PurpleEdge_BehaviorDescriptor extends Edge_BehaviorDescriptor {
  public PurpleEdge_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "Entities.structure.PurpleEdge";
  }
}
