package Entities.behavior;

/*Generated by MPS */


public class RedNode_BehaviorDescriptor extends Node_BehaviorDescriptor {
  public RedNode_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "Entities.structure.RedNode";
  }
}
